name: Pull request branch DEV
on:
  push:
    branches:
      - "dev_**"
jobs:
  build:
    runs-on: ubuntu-20.04
    if: "! contains(github.event.head_commit.message, 'UNIFICAR')"

    steps:
      - uses: actions/checkout@v3
        run: echo Ingresooo

